[platformio]
src_dir = main

[env:seeed_xiao_esp32s3]
platform = espressif32@6.9.0
framework = espidf
board = seeed_xiao_esp32s3
monitor_speed = 115200
upload_speed = 921600
board_build.flash_size = 8MB
board_build.partitions = partitions.csv
